# Generated by Django 5.0.3 on 2024-04-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='class_date',
            new_name='course_date',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='class_code',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='class_location',
            new_name='course_instructor',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='class_length',
            new_name='course_length',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='class_name',
            new_name='course_name',
        ),
        migrations.AddField(
            model_name='course',
            name='course_credit',
            field=models.CharField(default='3', max_length=2),
        ),
        migrations.AddField(
            model_name='course',
            name='course_place',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
