# Generated by Django 5.0.3 on 2024-04-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_class_date_course_course_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_date',
            field=models.DateField(),
        ),
    ]
