# Generated by Django 5.0.3 on 2024-04-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_course_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_date',
            field=models.CharField(max_length=10),
        ),
    ]
