# Generated by Django 5.0.3 on 2024-04-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_course_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_course', models.CharField(max_length=50)),
                ('assignment_title', models.CharField(max_length=250)),
                ('assignment_deadline', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='course_length',
            field=models.IntegerField(),
        ),
    ]
