# Generated by Django 5.0.3 on 2024-04-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_assignment_alter_course_course_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_length',
            field=models.IntegerField(default=0),
        ),
    ]
